import "tailwindcss/tailwind.css";
import type { AppProps } from "next/app";
import { useUser } from "./hook/useUser";
import { useEffect } from "react";
import { useRouter } from "next/router";
import Login from "../component/test/login";
import Head from "next/head";
import { Test } from "../component";

function MyApp({ Component, pageProps }: AppProps) {
  const { user } = useUser();
  const router = useRouter();
  useEffect(() => {
    !user && router.push("/");
  }, [user]);

  return (
    <div>
      {!user ? (
        <div>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <Test seachbar={true}>
            <Component {...pageProps} />
          </Test>
        </div>
      ) : (
        <Login />
      )}
    </div>
  );
}

export default MyApp;
